version: '3'
name: m1_mystore
networks:
  my-store-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

services:
  My-Store-PostgreSql:
    build: 
      context: ./My-Store-PostgreSql
      dockerfile: Dockerfile
    image: m1_custom_postgresql
    container_name: m1_custom_postgresql
    restart: unless-stopped
    networks:
      - my-store-network
    ports:
      - "5432:5432"
    volumes:
      - ./My-Store-PostgreSql/data:/var/lib/postgresql/data2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  My-Store-MongoSql:
    build: 
      context: ./My-Store-MongoSql
      dockerfile: Dockerfile
    image: m1_custom_mongo
    container_name: m1_custom_mongo
    restart: unless-stopped
    networks:
      - my-store-network
    ports:
      - "27017:27017"
    volumes:
      - ./My-Store-MongoSql/data:/var/lib/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  My-Store-Redis:
    build: 
      context: ./My-Store-Redis
      dockerfile: Dockerfile
    image: m1_custom_redis
    container_name: m1_custom_redis
    restart: unless-stopped
    networks:
      - my-store-network
    ports:
      - "6379:6379"
    volumes:
      - ./My-Store-Redis/data:/var/lib/redis/data

# docker-compose --env-file .env -f docker-compose.yml up -d --build
  
  # my-store-api_fastify:
  #   build:
  #     context: ./my-store-api_fastify
  #     dockerfile: Dockerfile
  #   image: m1_custom_api_fastify
  #   container_name: m1_custom_api_fastify
  #   restart: unless-stopped
  #   networks:
  #     - my-store-network
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - my-store-postgresql
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}

  # my-store:
  #   build:
  #     context: ./my-store
  #     dockerfile: Dockerfile
  #   image: m1_custom_my-store
  #   container_name: m1_custom_my-store
  #   restart: unless-stopped
  #   networks:
  #     - my-store-network
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - my-store-api_go
  #     - my-store-postgresql
  #   environment:
  #     - API_PATH_GO=${API_PATH_GO}
  #     - API_PATH_FASS=${API_PATH_FASS}
    
